"""
Structured schemas for the intelligence layer.
All LLM output is validated through these Pydantic models.
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


class RelevanceBucket(str, Enum):
    PRIME = "prime"
    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"
    SKIP = "skip"


class RoleBucket(str, Enum):
    TA_LEADER = "ta_leader"
    HR_LEADER = "hr_leader"
    RECRUITMENT = "recruitment"
    HR = "hr"
    HIRING_MANAGER = "hiring_manager"
    EXEC_TECH = "exec_tech"
    EXEC_BUSINESS = "exec_business"
    TECH_LEADER = "tech_leader"
    FOUNDER = "founder"
    OTHER = "other"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Dossier schemas
# ---------------------------------------------------------------------------

class ProspectSignal(BaseModel):
    """A single evidence signal with source and interpretation."""
    signal: str = Field(description="Observed fact or behaviour")
    interpretation: str = Field(description="Why this matters for outreach")
    confidence: int = Field(ge=0, le=100, description="Confidence in this signal 0-100")


class OutreachAngle(BaseModel):
    """A suggested angle for contacting this prospect."""
    angle: str = Field(description="One-line angle description")
    rationale: str = Field(description="Why this angle is appropriate")
    risk: Optional[str] = Field(default=None, description="Potential risk or pitfall")


class ProspectDossier(BaseModel):
    """
    Decision-ready profile for a single prospect.
    Generated by the LLM intelligence layer.
    """
    profile_url: str
    name: Optional[str]
    role_summary: str = Field(description="1-2 sentence role summary")
    company_context: str = Field(description="What we know about their company")
    relevance_verdict: str = Field(description="Why this person is (or isn't) worth contacting")
    relevance_bucket: RelevanceBucket
    confidence_score: int = Field(ge=0, le=100)

    signals: List[ProspectSignal] = Field(default_factory=list)
    outreach_angles: List[OutreachAngle] = Field(default_factory=list)

    recommended_action: str = Field(
        description="Specific next step: connect | message | email | skip"
    )
    priority_rank: int = Field(ge=1, description="1 = highest priority")

    reasoning: str = Field(description="Step-by-step reasoning for this assessment")
    caveats: List[str] = Field(default_factory=list)

    @field_validator("recommended_action")
    @classmethod
    def _validate_action(cls, v: str) -> str:
        valid = {"connect", "message", "email", "skip"}
        v_lower = v.strip().lower()
        if v_lower not in valid:
            return "skip"
        return v_lower


class DossierBatch(BaseModel):
    """Batch of dossiers for a single company."""
    company_name: str
    company_url: Optional[str]
    industry: Optional[str]
    employee_range: Optional[str]
    location: Optional[str]
    dossiers: List[ProspectDossier] = Field(default_factory=list)
    generated_at: str = Field(description="ISO datetime string")
    model_used: str


# ---------------------------------------------------------------------------
# Outreach message schemas
# ---------------------------------------------------------------------------

class OutreachMessage(BaseModel):
    """A generated outreach message for a specific prospect."""
    profile_url: str
    name: Optional[str]
    channel: str = Field(description="linkedin_connect | linkedin_message | email")

    subject: Optional[str] = Field(
        default=None, description="Subject line (email only)"
    )
    message_body: str = Field(description="Full message text")
    word_count: int = Field(ge=0)
    tone: str = Field(description="professional | warm | direct | consultative")

    personalization_hooks: List[str] = Field(
        default_factory=list,
        description="Specific personalisation elements used"
    )
    suggested_followup: Optional[str] = Field(
        default=None, description="Suggested follow-up action if no reply"
    )

    @field_validator("message_body")
    @classmethod
    def _set_word_count(cls, v: str) -> str:
        return v  # word_count set separately after init

    def compute_word_count(self) -> None:
        self.word_count = len(self.message_body.split())


class OutreachBatch(BaseModel):
    """Batch of outreach messages for a company."""
    company_name: str
    messages: List[OutreachMessage] = Field(default_factory=list)
    generated_at: str
    model_used: str
