/* Generated from .env - MySQL version */
INSERT INTO app_settings (setting_key, setting_value, description, config_type, updated_at_utc, updated_by)
VALUES
    ('DB_ECHO', 'false', 'Enable SQLAlchemy SQL logging.', 'database', UTC_TIMESTAMP(), 'env-sync'),
    ('DB_POOL_SIZE', '5', 'Database connection pool size.', 'database', UTC_TIMESTAMP(), 'env-sync'),
    ('DB_POOL_RECYCLE', '1800', 'Connection recycle time in seconds.', 'database', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_HEADLESS', 'false', 'Run browser in headless mode.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_FAST_MODE', 'true', 'Use speed-optimized browser behavior.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_NAV_TIMEOUT_MS', '15000', 'Browser navigation timeout in milliseconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_ACTION_TIMEOUT_MS', '6000', 'Browser action timeout in milliseconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_SCROLL_PAUSE_SEC', '0.25', 'Pause between scroll steps in seconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_LISTING_SCROLL_ROUNDS', '6', 'Scroll rounds for listing pages.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_POLITE_SLEEP_SEC', '0.1', 'Polite delay between browser operations in seconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_DETAIL_PAGE_DELAY_SEC', '0.4', 'Delay before opening each detail page in seconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_VIEWPORT_W', '1440', 'Browser viewport width in pixels.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('BROWSER_VIEWPORT_H', '900', 'Browser viewport height in pixels.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_CDP_ATTACH', 'true', 'Attach to an existing Chrome CDP endpoint.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_CDP_URL', '"http://127.0.0.1:9223"', 'Chrome DevTools Protocol endpoint URL.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_EXE', '"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"', 'Path to Chrome executable.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_USER_DATA_DIR', '"C:\\Users\\Public\\chrome-cdp-profile"', 'Chrome user data directory for persistent sessions.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_HEADLESS', 'false', 'Start managed Chrome in headless mode.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_STARTUP_WAIT_SEC', '2.5', 'Wait time after Chrome launch in seconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_NAV_TIMEOUT_MS', '30000', 'Chrome navigation timeout in milliseconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_ACTION_TIMEOUT_MS', '8000', 'Chrome action timeout in milliseconds.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('CHROME_RECOVERY_ATTEMPTS', '2', 'Chrome recovery retry attempts.', 'browser', UTC_TIMESTAMP(), 'env-sync'),
    ('LLM_PROVIDER', '"groq"', 'LLM provider (openai|gemini|groq).', 'llm', UTC_TIMESTAMP(), 'env-sync'),
    ('LLM_MODEL', '"openai/gpt-oss-20b"', 'LLM model name.', 'llm', UTC_TIMESTAMP(), 'env-sync'),
    ('LLM_TEMPERATURE', '0.2', 'LLM temperature for generation variability.', 'llm', UTC_TIMESTAMP(), 'env-sync'),
    ('LLM_MAX_TOKENS', '2000', 'Maximum LLM response tokens.', 'llm', UTC_TIMESTAMP(), 'env-sync'),
    ('LLM_TIMEOUT_SEC', '60', 'LLM request timeout in seconds.', 'llm', UTC_TIMESTAMP(), 'env-sync'),
    ('LLM_MAX_RETRIES', '3', 'LLM retry attempts on failure.', 'llm', UTC_TIMESTAMP(), 'env-sync'),
    ('LLM_RETRY_DELAY_SEC', '2.0', 'Delay between LLM retries in seconds.', 'llm', UTC_TIMESTAMP(), 'env-sync'),
    ('INGEST_LOCATION', 'null', 'Default ingestion location filter.', 'ingestion', UTC_TIMESTAMP(), 'env-sync'),
    ('INGEST_KEYWORDS', '["Python Developer"]', 'Default ingestion keywords used for keyword seeding.', 'ingestion', UTC_TIMESTAMP(), 'env-sync'),
    ('INGEST_MAX_JOB_AGE_DAYS', '7', 'Maximum job age (days) for ingestion.', 'ingestion', UTC_TIMESTAMP(), 'env-sync'),
    ('INGEST_MAX_JOBS_PER_KEYWORD', '20', 'Maximum jobs fetched per keyword run.', 'ingestion', UTC_TIMESTAMP(), 'env-sync'),
    ('RESEARCH_BATCH_SIZE', '10', 'Companies processed per research run.', 'research', UTC_TIMESTAMP(), 'env-sync'),
    ('RESEARCH_MAX_PROSPECTS', '20', 'Max prospects collected per company.', 'research', UTC_TIMESTAMP(), 'env-sync'),
    ('RESEARCH_MAX_PROFILES_ASSESS', '8', 'Top prospects deep-assessed per company.', 'research', UTC_TIMESTAMP(), 'env-sync'),
    ('RESEARCH_MIN_COMPANY_CONF', '70.0', 'Minimum confidence to accept company match.', 'research', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_ENABLED', 'true', 'Enable candidate hunt pipeline.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_JOB_BATCH_SIZE', '10', 'Jobs processed per candidate hunt run.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_MAX_PAGES_PER_QUERY', '5', 'LinkedIn search pages visited per query.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_MAX_CANDIDATES_PER_JOB', '60', 'Max candidate cards ingested per job.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_MAX_PROFILES_TO_ENRICH', '20', 'Max candidate profiles deep-enriched per job.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_MAX_QUERY_VARIANTS', '8', 'Max query variants generated per job.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_MIN_CARD_RELEVANCE_SCORE', '30', 'Minimum relevance score required to ingest a card.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_PROFILE_RETRY_LIMIT', '2', 'Retry limit for profile extraction/scoring failures.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_NAV_TIMEOUT_MS', '25000', 'Navigation timeout for candidate hunt pages.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_PAGE_SETTLE_MS', '900', 'Page settle wait after navigation/click in milliseconds.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_POLITE_DELAY_SEC', '0.5', 'Polite delay between candidate hunt page actions.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_LOCATION_FALLBACK', 'null', 'Fallback location added to candidate queries when needed.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_INCLUDE_COMPANY_IN_QUERY', 'false', 'Include company name in candidate query text.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('CANDIDATE_HUNT_INCLUDE_NEGATIVE_KEYWORDS', 'true', 'Include negative terms to reduce noisy profiles.', 'candidate_hunt', UTC_TIMESTAMP(), 'env-sync'),
    ('OUTREACH_RECRUITER_NAME', '"Ankit Gupta"', 'Recruiter name used in outreach personalization.', 'outreach', UTC_TIMESTAMP(), 'env-sync'),
    ('OUTREACH_AGENCY_NAME', '"gNxt Systems"', 'Agency name used in outreach personalization.', 'outreach', UTC_TIMESTAMP(), 'env-sync'),
    ('OUTREACH_FORCE_CHANNEL', '"linkedin_message"', 'Optional forced outreach channel.', 'outreach', UTC_TIMESTAMP(), 'env-sync'),
    ('OUTREACH_TEST_MODE_ENABLED', 'true', 'Send generated outreach to test inbox.', 'outreach', UTC_TIMESTAMP(), 'env-sync'),
    ('OUTREACH_TEST_RECIPIENT_EMAIL', '"ankit@gnxtsystems.com"', 'Recipient email used when outreach test mode is enabled.', 'outreach', UTC_TIMESTAMP(), 'env-sync'),
    ('OUTREACH_TEST_SUBJECT_PREFIX', '"[Outreach-Test Email - Automation Pipeline]"', 'Subject prefix for outreach test emails.', 'outreach', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_HOST', '"smtp.gmail.com"', 'SMTP server host.', 'email', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_PORT', '587', 'SMTP server port.', 'email', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_USERNAME', '"ankitgupta.imp21@gmail.com"', 'SMTP username/login for authentication.', 'email', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_PASSWORD', '"mrucgwwwerhhjkqw"', 'SMTP password or app password for authentication.', 'email', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_FROM_EMAIL', '"ankitgupta.imp21@gmail.com"', 'From email address for SMTP dispatch.', 'email', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_USE_TLS', 'true', 'Use STARTTLS for SMTP.', 'email', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_USE_SSL', 'false', 'Use implicit SSL for SMTP.', 'email', UTC_TIMESTAMP(), 'env-sync'),
    ('SMTP_TIMEOUT_SEC', '20', 'SMTP timeout in seconds.', 'email', UTC_TIMESTAMP(), 'env-sync')
AS new_values (setting_key, setting_value, description, config_type, updated_at_utc, updated_by)
ON DUPLICATE KEY UPDATE
    setting_value  = new_values.setting_value,
    description    = new_values.description,
    config_type    = new_values.config_type,
    updated_at_utc = new_values.updated_at_utc,
    updated_by     = new_values.updated_by;

SELECT ROW_COUNT() AS rows_affected;